get http://127.0.0.1:8000/api/settings
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NTE5OTc1NDMsImV4cCI6MTc1MjAwMTE0MywibmJmIjoxNzUxOTk3NTQzLCJqdGkiOiJBenlVVjZpVlJMUDVVSWNTIiwic3ViIjoiMSIsInBydiI6IjMyOTYzYTYwNmMyZjE3MWYxYzE0MzMxZTc2OTc2NmNkNTkxMmVkMTUifQ.FzANJzYQo720Xs7NRD9zk6VLoLtWBxTB9ABRzzKXmAA
