@TOKEN = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NTk4NTkyNjUsImV4cCI6MTc2MDQ2NDA2NSwibmJmIjoxNzU5ODU5MjY1LCJqdGkiOiJRaHhyb0F0d0xHSHZBbHdSIiwic3ViIjoiMSIsInBydiI6IjMyOTYzYTYwNmMyZjE3MWYxYzE0MzMxZTc2OTc2NmNkNTkxMmVkMTUifQ.-tDrFkAfSPWHTSPtSsdggbelaBx9y0D70J1RJVIXlL4
###
@URL = http://127.0.0.1:8000/api


POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "admin1234"
}
###

GET {{URL}}/sources/1
Authorization: Bearer {{TOKEN}}
###

POST {{URL}}/sources/1/notes
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "note": "This source provided 10 new clients this week",
    "date_added": "2025-10-03"
}
###

DELETE {{URL}}/employees/6
Authorization: Bearer {{TOKEN}}
###

POST {{URL}}/branches
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "name":"ahmed",
    "address":"ahmed"
}

###
POST {{URL}}/inquiries
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "name": "ahmed",
  "mobile": "01554300351",
  "email": "uyu365656@gmail.com",
  "nationality": "Egyption",
  "preferred_language": "Arabic",
  "address": "Elwasta",
  "company_name": "Motala",
  "business_category": "All",
  "country": "Egypt",
  "joining_date": "12-12-2025",
  "source_name": "PRO"
}

###
PUT {{URL}}/inquiries/1
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "status":"Inactive"
}
### 1)-
POST {{URL}}/inquiries/1/convert-to-customer/1
Authorization: Bearer {{TOKEN}}

### 2)-
DELETE {{URL}}/customersAttachments/1
Authorization: Bearer {{TOKEN}}

### 3)-
POST {{URL}}/inquiries/1/notes
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "note":"Hello",
    "note_date":"2025-10-14 14:49:01"
}

### 4)-
POST {{URL}}/inquiries/1/reminders
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "note":"Hello",
    "reminder_date":"2025-10-14 14:49:01",
    "reminder_type":"Mail"
}
### 5)-
PUT {{URL}}/sources/1
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "source_type":"Inactive"
}

###
GET {{URL}}/inquiries/1
Authorization: Bearer {{TOKEN}}


