get http://127.0.0.1:8000/api/auth/me
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NTE5MDYxNTUsImV4cCI6MTc1MTkwOTc1NSwibmJmIjoxNzUxOTA2MTU1LCJqdGkiOiJMdXBza0MzRFoxZFVvRFdXIiwic3ViIjoiMSIsInBydiI6IjMyOTYzYTYwNmMyZjE3MWYxYzE0MzMxZTc2OTc2NmNkNTkxMmVkMTUifQ.DaLWRZs8jalnR7d7n-DOUwA2XeiV4U3RnvzyzJtF2Mg
