get http://127.0.0.1:8000/api/dashboardStatistice
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NTIzMDEzMDYsImV4cCI6MTc1MjMwNDkwNiwibmJmIjoxNzUyMzAxMzA2LCJqdGkiOiI0QThSSnNCcXJSSkIyWXZJIiwic3ViIjoiMSIsInBydiI6IjMyOTYzYTYwNmMyZjE3MWYxYzE0MzMxZTc2OTc2NmNkNTkxMmVkMTUifQ.JYr8pU1ymCF__S9Rn8dd6WgvWSXjJJBvgOeSE2XupC8
